/**
 * Test: AI Prompt Builder - Suggestions & Inline Quiz guidelines
 * Verifies that the rules generated by the prompt builder include guidelines
 * for suggestions and inline quizzes.
 */

import { buildTeachPrompt } from '../src/utils/promptBuilder.js';

let passed = 0;
let failed = 0;

function assert(description, condition) {
  if (condition) {
    console.log(`  ✅ PASS: ${description}`);
    passed++;
  } else {
    console.error(`  ❌ FAIL: ${description}`);
    failed++;
  }
}

function runTests() {
  console.log('\n── Prompt Builder Integration Verification ──');

  const chunk = 'Photosynthesis is the process used by plants to convert light energy into chemical energy.';
  const profile = { level: 'beginner', studyLevel: 'High School', learningStyle: 'Visual' };
  const documentContext = { title: 'Intro to Biology', topics: ['Photosynthesis'] };

  const prompt = buildTeachPrompt(chunk, profile, 'understand', documentContext);

  assert('Prompt should contain DYNAMIC SUGGESTIONS tag instructions', prompt.includes('[SUGGESTIONS: ["Suggestion 1", "Suggestion 2", "Suggestion 3"]]'));
  assert('Prompt should contain INLINE MICRO-QUIZ tag instructions', prompt.includes('[QUIZ_QUESTION: {"question": "Question text?", "options": ["Option A", "Option B", "Option C", "Option D"], "answer": "Option A", "explanation": "Why Option A is correct"}]'));

  console.log(`\n── Results: ${passed} passed, ${failed} failed ──`);
  if (failed > 0) process.exit(1);
  else process.exit(0);
}

runTests();
